CREATE TABLE USER_ACCOUNT
(
    ID            VARCHAR(255) NOT NULL PRIMARY KEY,
    FIRST_NAME    VARCHAR(255) NOT NULL,
    LAST_NAME     VARCHAR(255) NOT NULL,
    PHONE_NUMBER  VARCHAR(20)  NOT NULL UNIQUE,
    IDENTIFY_CARD VARCHAR UNIQUE,
    DATE_OF_BIRTH DATE
);

CREATE TABLE WALLET
(
    ID       VARCHAR(255) NOT NULL PRIMARY KEY,
    BALANCE  FLOAT(50) NOT NULL,
    OWNER_ID VARCHAR(255) NOT NULL REFERENCES USER_ACCOUNT (ID)
);

CREATE TABLE MONEY_TRANSACTION
(
    ID                 VARCHAR(255) NOT NULL PRIMARY KEY,
    CREATED_DATE       TIMESTAMP    NOT NULL,
    LAST_UPDATED_DATE  TIMESTAMP    NOT NULL,
    WALLET_ID          VARCHAR      NOT NULL REFERENCES WALLET (ID),
    TARGET_ID          VARCHAR(255) NOT NULL,
    TARGET_TYPE        VARCHAR(255) NOT NULL,
    TRANSACTION_STATUS VARCHAR(255) NOT NULL,
    AMOUNT             FLOAT(50) NOT NULL,
    MESSAGE            VARCHAR(2000),
    BILL_TYPE          VARCHAR(255)
)